let leetcode_easy_src = 195;
let leetcode_medium_src = 506;
let leetcode_hard_src = 154;
let leetcode_total_solved_src = 855;
let leetcode_rating_src = 1951;
let leetcode_rank_src = "Knight";

let codeforces_rating_src = 1469;
let codeforces_rank_src = "Specialist";

const cur_date = new Date();

let work_experience = [
  {
    org_name: "ICRA Analytics Ltd.",
    starting_date: "August 2024",
    ending_date: "Present",
    starting_month: 8,
    starting_year: 2024,
    ending_month: cur_date.getMonth() + 1,
    ending_year: cur_date.getFullYear(),
    designation: "Associate Programmer",
    tech_stack: "Angular.js, Visual Basic, SQL, ASP.NET, MySQL",
  },
  {
    org_name: "ICRA Analytics Ltd.",
    starting_date: "September 2023",
    ending_date: "July 2024",
    starting_month: 9,
    starting_year: 2023,
    ending_month: 7,
    ending_year: 2024,
    designation: "Junior Developer (Apprentice)",
    tech_stack: "Visual Basic, SQL, MySQL",
  },
  {
    org_name: "Cognizant",
    starting_date: "August 2022",
    ending_date: "October 2022",
    starting_month: 8,
    starting_year: 2022,
    ending_month: 10,
    ending_year: 2022,
    designation: "Programmer Trainee",
    tech_stack: "JAVA, SQL, MySQL, RESTful API",
  },
];

let project = [
  {
    project_name: "In Touch (Find You 2.0)",
    tech_stack:
      "React.js, Node.js, Express.js, JAVA, SQL, Rest API, MySQL, MongoDB",
    github: "https://github.com/bhaskar4k/In-Touch",
    youtube: "https://www.youtube.com/watch?v=s7SPGE-qIiA",
    description: [
      "Created a fully functional social media website where users can login, upload, edit and delete post. Users can like, comment on posts, search and follow other users and also can engage in 1v1 chats.",
      "Implemented Socket.IO to have a real-time updation in like and comment box without reloading the page.",
      "Integrated a system to push notifications to all active users in real-time by maintaining a persistent connection between client and server using Socket.IO.",
      "Added a feature for users to search for other users efficiently, and achieved logarithmic search time. This was done by implementing binary search on local storage to have a log(n) search time and incorporated horizontal partitioning and indexing in the database to further reduce search time.",
      "Utilized Cropper.js to provide cropping and zooming features for images before they are uploaded as profile photos.",
      "Every user will have a newsfeed, generated by user-favourite tags. User-favorite tags are those tags that the user generally loves to add to his/her posts.",
    ],
  },
  {
    project_name: "Exam Portal",
    tech_stack: "React.js, JavaScript, Rest API, JAVA, JDBC, SQL, MySQL",
    github: "https://github.com/bhaskar4k/Project-Exam-Portal",
    youtube: "https://www.youtube.com/watch?v=hyR9b4N1NEA",
    description: [
      "Developed and implemented an web application with distinct admin and student portal, using React.js for the frontend and JAVA and Rest API for the backend.",
      "Implemented an in-app notification system featuring green, red, and orange popups based on user activity and validation, resulting in less user errors and better user experience.",
      "Designed an interactive user interface allowing the admin/student to create, login, and edit their profile information and providing full control on admin over scheduling exams and viewing the list of scheduled exams and results.",
      "Enabled students in facilitating their participation in any scheduled exam and granting access to view their results upon completion of the exam.",
    ],
  },
  {
    project_name: "Find You",
    tech_stack: "JSP, JavaScript, AJAX, JAVA, Servlet, JDBC, SQL, MySQL",
    github: "https://github.com/bhaskar4k/Find-You",
    youtube: "https://www.youtube.com/watch?v=Sh6LSSISPFo",
    description: [
      "Built a feature that generates a newsfeed for every active user, also the user can create, edit, delete post.",
      "Implemented a feature to do like, comment on any post. if a post is visible on screen then the like and comment box will be updating after each 10 seconds without reloading the page.",
      "Built a searchbar that will show search result(Other user’s profile) according to user’s input in realtime. Implemented this using AJAX and DOM manipulation. Also added a feature to follow/unfollow any existing user",
    ],
  },
];

let skills = [
  "C++",
  "JAVA",
  "Visual Basic",
  "JavaScript",
  "C#",
  "SQL",
  "HTML",
  "CSS",
  "React.js",
  "Node.js",
  "Express.js",
  "Bootstrap",
  "AJAX",
  "JSP",
  "Servlet",
  "JDBC",
  "RESTful API",
  "MySQL",
  "MongoDB",
];

let resume_gdrive_link =
  "https://drive.google.com/file/d/1eYNGNRig7PmUl1CDL4B_F-64X7fCPI87/view";

export {
  leetcode_easy_src,
  leetcode_medium_src,
  leetcode_hard_src,
  leetcode_total_solved_src,
  leetcode_rating_src,
  leetcode_rank_src,
  codeforces_rating_src,
  codeforces_rank_src,
  work_experience,
  project,
  skills,
  resume_gdrive_link,
};
